# Generated by Django 4.2.3 on 2023-07-08 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='people_you_may_kmow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
