# Generated by Django 4.2.3 on 2023-07-08 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_people_you_may_kmow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='people_you_may_kmow',
            new_name='people_you_may_know',
        ),
    ]
